name: tests

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ["8.4", "8.3", "8.2", "8.1"]
        laravel: ["12", "11", "10"]
        redis: ["7", "6"]
        ext: ["6.2.0", "6.0.2", "5.3.7"]
        stability: [ prefer-lowest, prefer-stable ]
        exclude:
          - php: 8.1
            laravel: 11
          - php: 8.1
            laravel: 12
          - php: 8.4
            laravel: 10
          - php: 8.4
            stability: prefer-lowest

    services:
      redis:
        image: redis:${{ matrix.redis }}
        ports:
          - 6379:6379
        options: --entrypoint redis-server

    name: PHP ${{ matrix.php }} Laravel ${{ matrix.laravel }} - ${{ matrix.stability }} with Ext ${{ matrix.ext }} - Redis ${{ matrix.redis }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: redis-${{ matrix.ext }}
          tools: composer:v2
          ini-values: error_reporting=E_ALL

      - name: Set Laravel version
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer require illuminate/redis:^${{ matrix.laravel }} --dev --no-interaction --no-update

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ matrix.php }}-${{ matrix.laravel }}-${{ matrix.stability }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --${{ matrix.stability }} --prefer-dist --no-interaction --no-progress

      - name: Execute phpcs
        run: php vendor/bin/phpcs

      - name: Execute tests
        run: php vendor/bin/phpunit

  bench:
    needs: [tests]
    uses: ./.github/workflows/bench.yml
